/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package has;

import static has.Checkavailable.url;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author SivaKesava1
 */
public class advancebooking extends javax.swing.JFrame {

    /**
     * Creates new form advancebooking
     */
    static String url = "jdbc:mysql://10.117.13.121:3306/dbhas";
      static String password = "89878";
      static String user = "kkk"; 
    public advancebooking() {
        initComponents();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel8.setVisible(false);
        jLabel4.setVisible(false);
        jLabel9.setVisible(false);
        jLabel7.setVisible(false);
        jButton1.setVisible(false);
        jButton7.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
         jButton6.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select the type of Room");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 240, 30);

        jComboBox1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bed  AC", "Single Bed Non AC", "Double Bed AC", "Double Bed Non AC" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(270, 20, 180, 30);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Period Of Stay");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 230, 30);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 150, 110, 30);

        jTextField1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 150, 180, 30);

        jLabel6.setFont(jLabel5.getFont());
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 200, 90, 32);

        jTextField2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 0), null));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(270, 200, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("This field cannot be empty");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 160, 150, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("This field cannot be empty");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 260, 150, 14);

        jLabel8.setFont(jLabel6.getFont());
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mobile Number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 250, 160, 30);

        jTextField3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), null));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(270, 250, 180, 30);

        jTextField4.setFont(jTextField3.getFont());
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 0), null));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(270, 80, 120, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("This field cannot be empty");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 210, 150, 14);

        jButton1.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 330, 80, 30);

        jButton2.setFont(jButton1.getFont());
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 330, 100, 30);

        jButton3.setFont(jButton1.getFont());
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Clear All");
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 380, 105, 30);

        jButton4.setFont(new java.awt.Font("Vijaya", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText(">>Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(526, 10, 87, 30);

        jButton5.setIcon(new javax.swing.ImageIcon("F:\\SEMESTER-4\\Software\\Java\\Travel\\calendar_icon.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(390, 80, 30, 27);

        jTextField5.setFont(jTextField4.getFont());
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(440, 80, 130, 25);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/has/calendar_icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(570, 80, 30, 27);

        jButton7.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 153));
        jButton7.setText("Check  Availability");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(440, 110, 160, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/has/Professional-powerpoint-templates-free-download-animated-desktop.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -10, 640, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String str1,str2,str3;
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        calendar cd=new calendar();     
        calendar.date=1;
        calendar.month=0;
        calendar.year=2015;
        
        
   			cd.btnSave.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
					String s;
                                        Calendar cz=Calendar.getInstance();
                                        cz.set(calendar.year,calendar.month, calendar.date);
                                        if((cz.getTimeInMillis()-System.currentTimeMillis())<0)
                                        {
                                     showMessageDialog(null, "This is a past date  ");
                                     jButton6.setEnabled(false);
                                     jTextField4.setText("");
                                     return;
                                        }
                                        long a=(cz.getTimeInMillis())- (System.currentTimeMillis());
                                        a=a/1000;
                                        a=a/60;
                                        a=a/60;
                                        a=a/24;
                                        if(a>60)
                                        {
                                             showMessageDialog(null, "Advanced Booking is not allowed for that period  ");
                                            jButton6.setEnabled(false);
                                             return;
                                        }
						s=(calendar.date.toString())+"-"+(((Integer)(calendar.month+1)).toString())+"-"+(calendar.year.toString()) ;
							jTextField4.setText(s);
                                                        jButton6.setEnabled(true);
						}           
					});
				  cd.setVisible(true);
                                  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        	jButton5.setEnabled(false);
                jButton6.setEnabled(true);
				
				cal=(Calendar) datecalendar.c.clone();
				calendar cd=new calendar();
				cal1=Calendar.getInstance();
				cd.btnSave.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
					String s;
						
						s=(calendar.date.toString())+"-"+(((Integer)(calendar.month+1)).toString())+"-"+(calendar.year.toString()) ;
						cal1.set(calendar.year,calendar. month, calendar.date);
						if((cal1.getTimeInMillis()-cal.getTimeInMillis())<0)
						{
							showMessageDialog(null, "Expected Check Out Date is before Check In Date  ");
                                                      jButton7.setVisible(false);
                                                        return;
						}
							jTextField5.setText(s);
                                                         jButton7.setVisible(true);
						}                 
					});
				 cd.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      z=jComboBox1.getSelectedIndex();
      jLabel5.setVisible(false);
        jButton5.setEnabled(true);
        jButton6.setEnabled(false);
        jLabel6.setVisible(false);
        jLabel8.setVisible(false);
        jLabel4.setVisible(false);
        jLabel9.setVisible(false);
        jLabel7.setVisible(false);
        jButton1.setVisible(false);
        jButton7.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton6.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          Connection conn = null;
          jButton5.setEnabled(false);
                jButton6.setEnabled(false);
          Statement stmt=null;
          
        try {
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
           // Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error in conn");
        }
        try {
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            //Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql="SELECT id,Value FROM Central"+" WHERE id=14";
         int presentday = 1;
        try {
            ResultSet rs = stmt.executeQuery(sql);
            presentday = rs.getInt("Value");
        } catch (SQLException ex) {
           //Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
           long a=(cal.getTimeInMillis())- (System.currentTimeMillis());
                                        a=a/1000; a=a/60;a=a/60; a=a/24;
            long b=(cal1.getTimeInMillis())- (System.currentTimeMillis());  
            b=b/1000;b=b/3600;b=b/24;
            
        try {
            System.out.println((int)a+presentday);
            System.out.println((int) b+presentday);
              System.out.println(z);
              room= Checkavailable.check((int)a+presentday,(int) b+presentday,z );
              System.out.println(room);
        } catch (SQLException ex) {
            Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(room!=null)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel8.setVisible(true);
        jLabel4.setVisible(false);
        jLabel9.setVisible(false);
        jLabel7.setVisible(false);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        }
        else
        {
      	showMessageDialog(null, "Please Try for other Duration  ");
        jLabel5.setVisible(false);
        jButton5.setEnabled(true);
        jButton6.setEnabled(false);
        jLabel6.setVisible(false);
        jLabel8.setVisible(false);
        jLabel4.setVisible(false);
        jLabel9.setVisible(false);
        jLabel7.setVisible(false);
        jButton1.setVisible(false);
        jButton7.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton6.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(advancebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(advancebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(advancebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(advancebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new advancebooking().setVisible(true);
            }
        });
    }
    Calendar cal,cal1,present;
    int z;
    String room;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
