/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package has;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MAHANKALI SAKETH
 */
public class ChangeUAP extends javax.swing.JFrame {

    /**
     * Creates new form ChangeUAP
     */
    public ChangeUAP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setForeground(new java.awt.Color(0, 102, 204));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 30));

        t2.setForeground(new java.awt.Color(0, 102, 204));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 30));

        t3.setForeground(new java.awt.Color(0, 102, 204));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 160, 30));

        c1.setForeground(new java.awt.Color(0, 102, 204));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MANAGER", "RECEPTIONIST", "CATERING SERVICES" }));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, 30));

        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("NEW PASSWORD:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("NEW USERNAME:-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("YOUR OLD PASSWORD:-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("CHANGE U/P OF:-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHANKALI SAKETH\\Desktop\\background3.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = (String)c1.getSelectedItem();
        String str1 = t1.getText();
        String str2 = t2.getText();
        String str3 = t3.getText();
        String m1 = "";
        String m2 = "";
        String r1 = "";
        String r2 = "";
        String c1 = "";
        String c2 = "";
        try 
        {
           
           Connection con =  Connectiond.getconn();
           Statement stmt = con.createStatement();
           String sql = "SELECT id,Value FROM central";
           ResultSet rs = stmt.executeQuery(sql);
           
           int id;
           while(rs.next())
           {
               id  = rs.getInt("id");
               /*byte[] buf = rs.getBytes("copyDetails");
                ObjectInputStream o = new ObjectInputStream(new ByteArrayInputStream(buf));
                ArrayList<SubBook> copyDetails = (ArrayList<SubBook>) o.readObject();*/
               if(id == 1)
               {
                    m1 = rs.getString("Value");
               }
               if(id == 2)
               {
                    m2 = rs.getString("Value");
               }
               if(id == 3)
               {
                    c1 = rs.getString("Value");
               }
               if(id == 4)
               {
                    c2 = rs.getString("Value");
               }
               if(id == 5)
               {
                    r1 = rs.getString("Value");
               }
               if(id == 6)
               {
                    r2 = rs.getString("Value");
                    break;
               }
                 
            }
          }
          catch(Exception ex)
          {
              
          }
         if(str.equals("MANAGER"))
         {
            if(str1.equals(m2) )
            {
                try
               {
            
                 String updatestr = "UPDATE central SET Value = ?  WHERE id = 1";
                 PreparedStatement p = Connectiond.getconn().prepareStatement(updatestr);
                 p.setObject(1,str2);
                 p.executeUpdate();
                 updatestr = "UPDATE central SET Value = ?  WHERE id = 2";
                 PreparedStatement pp = Connectiond.getconn().prepareStatement(updatestr);
                 pp.setObject(1,str3);
                 pp.executeUpdate();
                 JOptionPane.showMessageDialog(rootPane,"Successfully updated");
              }
              catch(Exception ex)
              {
                  ex.printStackTrace();
              }
            }
            else
            { 
                JOptionPane.showMessageDialog(rootPane,"Entered password is wrong");
            }
         }
        else if(str.equals("RECEPTIONIST"))
        {
            if(str1.equals(r2) )
            {
               try
               {
            
                  String updatestr = "UPDATE central SET Value = ?  WHERE id = 5";
                  PreparedStatement p = Connectiond.getconn().prepareStatement(updatestr);
                  p.setObject(1,str2);
                  p.executeUpdate();
                  updatestr = "UPDATE central SET Value = ?  WHERE id = 6";
                  PreparedStatement pp = Connectiond.getconn().prepareStatement(updatestr);
                  pp.setObject(1,str3);
                  pp.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane,"Successfully updated");
              }
              catch(Exception ex)
              {
                  ex.printStackTrace();
              }
            }
            else
            { 
                JOptionPane.showMessageDialog(rootPane,"Entered password is wrong");
            }
        }
        else if(str.equals("CATERING SERVICES"))
        {
           if(str1.equals(c2) )
            {
               try
               {
            
                  String updatestr = "UPDATE central SET Value = ?  WHERE id = 3";
                  PreparedStatement p = Connectiond.getconn().prepareStatement(updatestr);
                  p.setObject(1,str2);
                  p.executeUpdate();
                  updatestr = "UPDATE central SET Value = ?  WHERE id = 4";
                  PreparedStatement pp = Connectiond.getconn().prepareStatement(updatestr);
                  pp.setObject(1,str3);
                  pp.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane,"Successfully updated");
              }
              catch(Exception ex)
              {
                  ex.printStackTrace();
              }
            }
            else
            { 
                JOptionPane.showMessageDialog(rootPane,"Entered password is wrong");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
