/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package has;

import static has.Url.url;
import static has.Url.user;
import static has.Url.password;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author SivaKesava1
 */
public class Checkin extends javax.swing.JFrame {

    /**
     * Creates new form Checkin
     */
    public Checkin() {
        initComponents();
        jButton7.setVisible(false);
        jTextField4.setEditable(false);
        jTextField4.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Select the type of Room");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bed  AC", "Single Bed Non AC", "Double Bed AC", "Double Bed Non AC" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jButton4.setFont(new java.awt.Font("Vijaya", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText(">>Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jTextField4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 0), null));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/has/calendar_icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 30, 30));

        jButton7.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 153));
        jButton7.setText("Check  Availability");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Expected Check Out Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/has/Ibis-Luton-reception-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                z=jComboBox1.getSelectedIndex();
                jButton7.setVisible(false);
                jTextField4.setText("");
                
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        calendar cd=new calendar();
        calendar.date=1;
        calendar.month=0;
        calendar.year=2015;

        cd.btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String s;
                Calendar cz=Calendar.getInstance();
                Calendar cas=Calendar.getInstance();
                cz.set(calendar.year,calendar.month, calendar.date);
                if((cz.getTimeInMillis()-System.currentTimeMillis())<0)
                {
                    showMessageDialog(null, "This is a past date  ");
                    jButton7.setVisible(false);
                    jTextField4.setText("");
                    return;
                }
                c=cas.getTimeInMillis();
                long a=(cz.getTimeInMillis())- (c);
                a=a/1000;
                a=a/60;
                a=a/60;
                a=a/24;
                if(a==0)
                {
                     showMessageDialog(null, "You cannot check out today only  ");
                    jButton7.setVisible(false);
                    return;
                }
                if(a>60)
                {
                    showMessageDialog(null, "You cannot check In for that long  ");
                    jButton7.setVisible(false);
                    return;
                }
                s=(calendar.date.toString())+"-"+(((Integer)(calendar.month+1)).toString())+"-"+(calendar.year.toString()) ;
                jTextField4.setText(s);
                jButton7.setVisible(true);
            }
           
        });
        cd.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {                                         
            // TODO add your handling code here:
            Connection conn = null;
            jButton5.setEnabled(false);
            
            Statement stmt=null;
            
            try {
                conn = DriverManager.getConnection(url, user, password);
            } catch (SQLException ex) {
                // Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Error in conn");
            }
            try {
                stmt = conn.createStatement();
            } catch (SQLException ex) {
                //Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql12 = "SELECT id,Value FROM central";
            ResultSet rs12 = stmt.executeQuery(sql12);
            int id;
            int presentday = 1;
            while(rs12.next())
            {
                id  = rs12.getInt("id");
                if(id ==14)
                {
                    
                    presentday = rs12.getInt("Value");
                    
                }
            }
            cal=(Calendar) datecalendar.c.clone();
            b=(cal.getTimeInMillis())- (c);  
            b=b/1000;b=b/3600;b=b/24;
            
            try {
                /*
                System.out.println((int) b+presentday);
                System.out.println(z);
                System.out.println(presentday);*/
                a=presentday;
                b=b+presentday;
                System.out.println(a);
                System.out.println(b);
                System.out.println(z);
                room= Checkavailable.check(presentday,(int) b,z );
                // System.out.println(room);
            } catch (SQLException ex) {
                //    Logger.getLogger(advancebooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(room!=null)
            {
                
                // new Checkinlink(a,b,room,z).setVisible(true);
                //  ck.setVisible(true);
                new NewJFrame(a,b,room,z).setVisible(true);
                dispose();
            }
            else
            {
                showMessageDialog(null, "Please Try for other Duration  ");
                jButton5.setEnabled(true);
                jTextField4.setText("");
                jButton7.setVisible(false);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Checkin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkin().setVisible(true);
            }
        });
    }
Calendar cal,cas,cal1,present;
    int z;   
    long a,b,c;
    String room;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
