/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package has;

import java.io.ByteArrayInputStream;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MAHANKALI SAKETH
 */
public class UpdateDiscount extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDiscount
     */
    public UpdateDiscount() {
        initComponents();
        try{
             Connection con =  Connectiond.getconn();
             Statement stmt = con.createStatement();
             String sql = "SELECT id,Value FROM central";
             ResultSet rs = stmt.executeQuery(sql);
             byte[] arr;
             Vector value = new Vector();
             int id;
             while(rs.next())
             {
                id  = rs.getInt("id");
               /*byte[] buf = rs.getBytes("copyDetails");
               ObjectInputStream o = new ObjectInputStream(new ByteArrayInputStream(buf));
               ArrayList<SubBook> copyDetails = (ArrayList<SubBook>) o.readObject();*/
                if(id == 13)
                {
                  arr = rs.getBytes("Value");
                  ObjectInputStream o = new ObjectInputStream(new ByteArrayInputStream(arr)); 
                  value= (Vector)o.readObject();
                  break;
               }
               
              }
          
             t1.setText(Double.toString((double)value.get(0)));
             t3.setText(Double.toString((double)value.get(1)));
             t5.setText(Double.toString((double)value.get(2)));
             t7.setText(Double.toString((double)value.get(3)));
             t9.setText(Double.toString((double)value.get(4)));
             t11.setText(Double.toString((double)value.get(5)));
        }
        
        catch(Exception ex)
        {
            ex.printStackTrace();
            System.out.println("Exception caught");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        t1.setEditable(false);
        t1.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 60, -1));

        t3.setEditable(false);
        t3.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 60, -1));

        t5.setEditable(false);
        t5.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 60, -1));

        t7.setEditable(false);
        t7.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 60, -1));

        t9.setEditable(false);
        t9.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 60, -1));

        t11.setEditable(false);
        t11.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 60, -1));

        t2.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 60, -1));

        t4.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 60, -1));

        t6.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 60, -1));

        t8.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 60, -1));

        t10.setForeground(new java.awt.Color(0, 51, 204));
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 60, -1));

        t12.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 60, -1));

        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Enter New");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Before");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Limit4:-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Limit3:-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Limit2:-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, 20));

        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Limit1:-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Bill:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 50, -1));

        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Frequeny:-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHANKALI SAKETH\\Desktop\\discount2.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHANKALI SAKETH\\Desktop\\background3.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str1 = t2.getText();
        String str2 = t4.getText();
        String str3 = t6.getText();
        String str4 = t8.getText();
        String str5 = t10.getText();
        String str6 = t12.getText();
        Vector value = new Vector();
        double d1=0.0;
        double d2=0.0;
        double d3=0.0;
        double d4 =0.0;
        double d5 =0.0;
        double d6 =0.0;
        
        try
        {
            d1 = Double.parseDouble(str1);
            d2 = Double.parseDouble(str2);
            d3 = Double.parseDouble(str3);
            d4 = Double.parseDouble(str4);
            d5 = Double.parseDouble(str5);
            d6 = Double.parseDouble(str6);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane,"invalid entries ..please enter again");
        }
        try
        {
             Connection con =  Connectiond.getconn();
             Statement stmt = con.createStatement();
             String sql = "SELECT id,Value FROM central";
             ResultSet rs = stmt.executeQuery(sql);
             byte[] arr;
             int id;
             while(rs.next())
             {
                id  = rs.getInt("id");
               /*byte[] buf = rs.getBytes("copyDetails");
               ObjectInputStream o = new ObjectInputStream(new ByteArrayInputStream(buf));
               ArrayList<SubBook> copyDetails = (ArrayList<SubBook>) o.readObject();*/
                if(id == 13)
                {
                  arr = rs.getBytes("Value");
                  ObjectInputStream o = new ObjectInputStream(new ByteArrayInputStream(arr)); 
                  value= (Vector)o.readObject();
                  break;
               }
               
              }
        }
        catch(Exception ex)
        {
            
        }
        value.set(0,d1);
        value.set(1,d2);
        value.set(2,d3);
        value.set(3,d4);
        value.set(4,d5);
        value.set(5,d6);
        String updatestr = "UPDATE central SET Value = ?  WHERE id = 13";
        try {
            PreparedStatement p = Connectiond.getconn().prepareStatement(updatestr);
            p.setObject(1,value);
             p.executeUpdate();
              JOptionPane.showMessageDialog(rootPane,"Successfully updated");
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDiscount.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDiscount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
